### ISSUE TITLE
Info pages for some MAL entries (consistently) fail to load

### ISSUE THREAD

**Issue by aphirst** [AnimeNeko/Atarashii#443] opened 2015-09-18 23:30 UTC
I'm using the `2.1.1` release available here from GitHub, on a CM 12.1 (nightly) device without GApps.

I am experiencing a problem, by which the Info/Description pages for some anime/manga in MAL fail to load, with the following error message on the bottom of the screen:
``
Atarashii can't load the details
``

This seems to be deterministic - if I clear the App's cache and Local Data, reboot the device, and try again - the same entries fail to load. Also reproducible across a few different WiFi networks I have access to, and the Mobile Internet.

When I have a bit more time, I'll try to compile a short list of some entries which always do load, and respectively some which always don't. But otherwise, I'm not sure what other information I should provide - nonetheless I'm keen to if someone lets me know what I should share/do. :smile:

**Comment by motokochan** [comment] 2015-09-19 02:29
A list of a few titles that show this issue would be greatly appreciated.

**Comment by aphirst** [comment] 2015-09-19 10:46
Well for me, it feels like the majority of things.

Entries that work:
* Mawaru Pengruindrum
* Toaru Kagaku no Railgun
* Golden Boy
* Shakugan no Shana Specials
* Hetalia World Series
* Durarara!! Specials
* Sayonara Zetsubou Sensei
* Strike Witches

Entries that don't
* .hack//Sign
* Akikan!
* Azumanga Daioh
* Cardcaptor Sakura
* Chobits
* Gosick
* Hanamaru Youchien
* Hellsing Ultimate
* Karigurashi no Arrietty
* Lodoss-tou Senki
* Serial Experiments Lain
* Toradora!
* Yuru Yuri
* Zero no Tsukaima
* Zero no Tsukaima F

I can keep adding to this if you really want, but I can reproduce this consistently. It'd be interesting to know if others have this problem too.

**Comment by ratan12** [comment] 2015-09-19 12:35
Confirmed that it is not an API issue.

In my custom build it loads fine, it could be a bug that I fixed after rewriting some parts. To be 100% sure we need to try to reproduce it on the same version as @aphirst.

I will look into this as soon I am done with the DB changes.

**Comment by motokochan** [comment] 2015-09-21 23:26
Running a quick test with 2.1.1 on a N9 with AOSP (factory image) and not seeing any issues with the titles. Some are on my list, some are not. Maybe this is CM-related? I'd love to see a logcat when the error occurs.

**Comment by aphirst** [comment] 2015-09-22 06:07
I tried to generate a log using `logcat` locally on the device (in the terminal Emu I ran `logcat > filename.txt` then switched to Atarashii and opened a few Anime entries), but the file I got out doesn't seem to be especially relevant: https://a.pomf.cat/ycsxqz.txt (I opened one "not working" then one "working" entry).

I tried it again (2 or 3 non-working, 2 working) and the log still seems irrelevant https://a.pomf.cat/dcoija.txt . I guess I'm doing something wrong? It looks like it's only logging stuff to do with the terminal emulator, which is obviously useless...

**Comment by aphirst** [comment] 2015-09-22 06:22
OK I think I got it, I gave the terminal emulator superuser priviliges. https://a.pomf.cat/njclmt.txt

I did a clear of Atarashii's Cache and Data, opened it fresh, enabled the log, tabbed into Atarashii, and opened the following 5 entries:
* Elfen Lied (didn't load)
* Elfen Lied Special (didn't load)
* Ergo Proxy (didn't load)
* Eve no Jikan (did load)
* Fate Kaleid Liner Prisma Ilya (did load)

**Comment by ratan12** [comment] 2015-09-22 08:27
Awesome!

NetworkTask.doInBackground(): ANIME-task API error on job GETDETAILS: 200 - OK W/System.err( 4124): retrofit.RetrofitError: com.google.gson.JsonSyntaxException: java.lang.NumberFormatException: Expected an int but was 5.4 at line 1 column 2697 path $.storage_value W/System.err( 4124): 	at 

This is your error and this is enough info to find the cause!

**Comment by motokochan** [comment] 2015-09-22 16:24
MAL supports floats on storage value, and the API documents that it will pass a "decimal number". The application should probably be fixed.

**Comment by ratan12** [comment] 2015-09-22 16:34
@aphirst I will release this week a quickpatch. Thanks for your help to find this issue!

**Comment by aphirst** [comment] 2015-09-22 16:41
@ratan12 No problem! Happy to help in the ways I can.
@motokochan How come, then, that it seemed to work fine on your side with AOSP? I'm curious to know :smile:

**Comment by ratan12** [comment] 2015-09-22 16:44
The cause was the storage value. We do not use that feature so we had no problems ;)

**Comment by motokochan** [comment] 2015-09-22 16:46
What he said. I don't usually set storage for the titles I watch. I think I may only have it on one title that I used for testing the API parsing.

**Comment by ratan12** [comment] 2015-09-25 13:38
The fix is ready. Once the API got updated I will release it.

**Comment by ratan12** [comment] 2015-09-27 12:18
@aphirst The fix got released yesterday.

I will not close this issue because it is still in version 2.2 which also must be fixed.

**Comment by ratan12** [comment] 2015-11-14 18:48
Fixed by 58a8dd8

**Closed by ratan12** 2015-11-14 18:48 UTC
Labels: bug
